### ISSUE TITLE
UI components links on the main website are broken

### ISSUE THREAD

**Issue by Jasius** [esr360/One-Nexus#17]
Throws me to github 404 https://github.com/esr360/One-Nexus/tree/master/src/modules/elements/forms

**Comment by esr360** [comment]
Thanks for bringing this to my attention - will get this fixed asap.

Correct link is currently: https://github.com/esr360/One-Nexus/tree/master/src/ui/modules/elements/forms

**Comment by esr360** [comment]
Appropriate issue raised as esr360/One-Nexus-Homepage#1
