### ISSUE TITLE
theme.json unreadable

### ISSUE THREAD

**Issue by rowbe** [esr360/One-Nexus#18]
"Line 8: File to import not found or unreadable: ui/themes/One-Nexus/theme.json."

After successfully installing and double-checking all dependencies locally, I receive the error message above when I run SASS watch command. 
Someone please help a bro.

**Comment by esr360** [comment]
Are you using Ruby Sass, not Node-Sass or LibSass?

Also, have you installed the [sass-json-vars](https://github.com/vigetlabs/sass-json-vars) gem?

Finally, are you using a specific release/version of One-Nexus, or just the master branch?

I'm in the middle up updating One-Nexus to be compatible with Node-Sass, when this happens you won't need to install the above `sass-json-vars` gem.

**Comment by rowbe** [comment]
@esr360 I have Ruby SASS. I have sass-json-vars installed. I believe I cloned the Master branch (git clone https://github.com/esr360/One-Nexus.git). 

When is the update be complete?

**Comment by esr360** [comment]
The update will be complete in 3-6 days.

Are you using the built in grunt tools to build One-Nexus, or are you using some other method?

The error means that the sass compiler isn't using sass-json-vars, if you are just runing the normal sass watch command from the terminal, you will need to add `-r sass-json-vars`, e.g:

`sass /PATH/TO/app.scss -r sass-json-vars` - from the bottom of this page: https://github.com/vigetlabs/sass-json-vars

**Comment by rowbe** [comment]
I'm only using built-in tools, still no success with `sass /PATH/TO/app.scss -r sass-json-vars`.

**Comment by rowbe** [comment]
"My code doesn't work, but I don't know why..."
(20 odd tries later): "My code works, but I don't know why..."

Everything works now, after restarting the whole process using an older copy. Thanks a bunch!

**Comment by esr360** [comment]
Hmmm, very odd indeed! If you do figure out what was wrong be sure to let me know so I can update the docs! Cheers
