### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by vaishnavmhetre** [esr360/One-Nexus#19]
All links providing info about Elements, Objects as well as Utilities on page[https://github.com/esr360/One-Nexus/wiki/UI-Modules](https://github.com/esr360/One-Nexus/wiki/UI-Modules) hit a 404.

**Comment by esr360** [comment]
Thank you for raising.

**Comment by vaishnavmhetre** [comment]
@esr360 You're welcome.

**Comment by rataman098** [comment]
Any updates on this? @esr360

**Comment by vaishnavmhetre** [comment]
No problems at visiting[ https://github.com/esr360/One-Nexus/wiki/UI-Modules](UI modules) now on. Closing thread.

**Comment by rataman098** [comment]
> 
> 
> No problems at visiting[ https://github.com/esr360/One-Nexus/wiki/UI-Modules](UI modules) now on. Closing thread.

Have you tried opening any of the Elements/Objects/Utilities links? They still give me Error 404...

**Comment by vaishnavmhetre** [comment]
I wasn't able to access apex page too, - (reason the issue raised for). If it still persists, modify issue and reopen it.

**Comment by vaishnavmhetre** [comment]
Anyway it is not under active development. So least consideration for it. No offence!

**Comment by esr360** [comment]
One-Nexus is being re-built from scratch (under [develop branch](https://github.com/esr360/One-Nexus/tree/develop), and will be moved to https://github.com/One-Nexus/) and is almost finished but taken longer than planned - the current documentation will become out of date when this happens, but it is attempting to point to the modules here:

https://github.com/esr360/One-Nexus/tree/master/src/ui/modules

With documentation available under individual modules in the README.md, e.g:

https://github.com/esr360/One-Nexus/tree/master/src/ui/modules/utilities/colors

Apologies for not keeping the current wiki up-to date; I will update the links now, but bear in mind it will soon become obsolete with version 4 of One-Nexus.

**Comment by vaishnavmhetre** [comment]
> One-Nexus is being re-built from scratch (under [develop branch](https://github.com/esr360/One-Nexus/tree/develop), and will be moved to https://github.com/One-Nexus/) and is almost finished but taken longer than planned - the current documentation will become out of date when this happens, but it is attempting to point to the modules here:
> 
> https://github.com/esr360/One-Nexus/tree/master/src/ui/modules
> 
> With documentation available under individual modules in the README.md, e.g:
> 
> https://github.com/esr360/One-Nexus/tree/master/src/ui/modules/utilities/colors
> 
> Apologies for not keeping the current wiki up-to date; I will update the links now, but bear in mind it will soon become obsolete with version 4 of One-Nexus.

Response to issue is appreciated. I loved your project and working aesthetics, but the documentation made me go away. I'm planning to use it for an enterprise project, so hopefully it keeps up with assured utilities and I'm curiously waiting for its release.
