### ISSUE TITLE
[Possible Feature Request] - Different column sizes at different viewports

### ISSUE THREAD

**Issue by green-arrow** [esr360/One-Nexus#8]
In Bootstrap 3, you are able to specify a different row setup based on viewport size. For example, I can do:

```html
<div class="row">
    <div class="col-lg-4 col-md-3 col-sm-6">...</div>
    <div class="col-lg-4 col-md-3 col-sm-2">...</div>
    ...
</div>
```

Maybe I've just missed it in the documentation, but it doesn't appear that this is something the grid system of One Nexus is able to accomplish.

Has anyone thought of including this functionality in the One Nexus grid system? Or has this been intentionally excluded? Or have I just missed it in the documentation?

**Comment by esr360** [comment]
This feature is implemented in version 3.0.0 which can be tested on master.
